# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#

version: 2
jobs:
  build-deploy:
    machine:
      enable: true
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./bin/build
      - run: ./bin/deploy
  integration_test:
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: ./bin/test

workflows:
  version: 2
  build_test_deploy_release:
    jobs:
      - integration_test
      - build-deploy:
        requires:
          - integration_test
